[package]
name = "cll"
version = "0.1.1"
edition = "2018"
repository = "https://github.com/goiw111/cll"
license = "MIT OR Apache-2.0"
description = "circular linked list"

[dependencies]
serde = "1"
toml = "0.5"
serde_derive = "1.0"
